### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by HandsomeDevilv112** [justinmichaud/rust-nes-emulator#1]
I gotta tell you, I've been just dreaming of getting my hands on this bit of code here for quite some time now. 
But, I gotta apologize. I've worked with some machine learning projects, but I'm punching outside my weight class pretty desperately right now. 
If I may, I'd like to request just a bit of help on (non torch-rnn) dependencies. Just enough information that I can start looking up error codes 
Any help is appreciated

**Comment by justinmichaud** [comment]
Sure. What specific errors are you getting?

**Comment by HandsomeDevilv112** [comment]
My apologies for dropping the ball on this. 
If I genuinely decide to really invest in this, I'll pick up the book. 
Closing.
