### ISSUE TITLE
Mario levels ASCII

### ISSUE THREAD

**Issue by 0xMelkor** [justinmichaud/rust-nes-emulator#2]
Hi @justinmichaud,
i'd like to use this repo to extract original Mario levels as ASCII text. This is for training my own LSTM network. Is it possible with this code base?

Thank you so much

**Comment by justinmichaud** [comment]
Yep. Check the example output https://github.com/justinmichaud/rust-nes-emulator/blob/master/assets/defaults_20e_20x/my_data.txt and the code to generate it at https://github.com/justinmichaud/rust-nes-emulator/blob/master/src/level_out.rs

If you want to output levels that I haven't already added to level_out.rs, grab them from a dissassembly (search for one of the existing levels in the file to see where to grab them from). You may need to add extra options to the level_out file to read underground and castle levels, which the documentation at the root of the project may be helpful with. Just keep in mind that that documentation is for the super nintendo port, so not everything is completely correct.

**Comment by insanediv** [comment]
Thank you Justin. Awesom

**Comment by 0xMelkor** [comment]
Thank you Justin. Awesome work
